# Generated by Django 5.2.7 on 2025-10-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
