# Generated by Django 5.2.7 on 2025-10-07 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('users', '0002_user_needs_password_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('emergency_contact_no', models.CharField(max_length=20)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='admin/profiles/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('management_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admins', to='student.academicdepartment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
