# Generated by Django 5.2.7 on 2025-10-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
    ]
