# Generated by Django 5.2.7 on 2025-10-05 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Computer Science & Engineering', 'Computer Science & Engineering'), ('Bachelor of Business Administration', 'Bachelor of Business Administration')], max_length=200)),
                ('code', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('BBA', 'Bachelor of Business Administration')], max_length=10, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='student.academicfaculty')),
            ],
            options={
                'ordering': ['academic_faculty', 'name'],
                'unique_together': {('name', 'academic_faculty')},
            },
        ),
        migrations.CreateModel(
            name='AcademicSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=20)),
                ('year', models.IntegerField()),
                ('start_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('end_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('contact_no', models.CharField(max_length=20)),
                ('emergency_contact_no', models.CharField(max_length=20)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('guardian_number', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='students/profiles/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='student.academicdepartment')),
                ('admission_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_students', to='student.academicsemester')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['academic_department', 'student_id'], name='student_stu_academi_dbb903_idx'), models.Index(fields=['admission_semester'], name='student_stu_admissi_2618e4_idx'), models.Index(fields=['is_deleted'], name='student_stu_is_dele_6bbfbf_idx')],
            },
        ),
    ]
