# Generated by Django 5.2.7 on 2025-10-10 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "faculty_id",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("Professor", "Professor"),
                            ("Associate Professor", "Associate Professor"),
                            ("Assistant Professor", "Assistant Professor"),
                            ("Lecturer", "Lecturer"),
                            ("Senior Lecturer", "Senior Lecturer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("contact_no", models.CharField(max_length=20)),
                ("emergency_contact_no", models.CharField(max_length=20)),
                ("present_address", models.TextField()),
                ("permanent_address", models.TextField()),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="faculty/profiles/"
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faculty_members",
                        to="student.academicdepartment",
                    ),
                ),
                (
                    "academic_faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faculty_members",
                        to="student.academicfaculty",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["academic_department", "faculty_id"],
                        name="student_fac_academi_1557eb_idx",
                    ),
                    models.Index(
                        fields=["academic_faculty"],
                        name="student_fac_academi_a09d66_idx",
                    ),
                    models.Index(
                        fields=["is_deleted"], name="student_fac_is_dele_684d89_idx"
                    ),
                ],
            },
        ),
    ]
